### ISSUE TITLE
List servers Bouncer is installed on and user count

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/bouncer#194]
To be able to market Bouncer effectively, we need to know details about where Bouncer is installed.
* This will live on the existing stats page
* UI should be text-only like we already have

```
Server                                  Users
Interlock                              800
Assured Network                1100
```

Specifically, this will help me:
* Reach out to servers that have stopped using Bouncer
* Prioritize requests from servers that ARE using Bouncer
* Understand who exactly is even using Bouncer
  * Like, have servers we HAVEN't reached out to started using Bouncer bc they got a link?
  * Or are there multiple test servers it's still installed on that we've forgotten about?

**Comment by jmercouris** [comment]
If so, then I believe it will behoove us to make the statistics page private. We don't want to give out information about where Bouncer is running to third parties.

**Comment by jmercouris** [comment]
What do you think?

**Comment by DecentralizedDan** [comment]
yeah, I'll make a ticket for that
